In [1]:
import ipywidgets as widgets
import numpy as np
from ipywidgets import interact, interactive, fixed, interact_manual
import AL_Fct as al

r=widgets.RadioButtons(
    options=['Eij', 'Ei(alpha)', 'Eij(alpha)'],
#     value='pineapple',
    description='Opération:',
    disabled=False
)


alpha=widgets.Text(
    value='1',
    description='Coeff. alpha:',
    disabled=False
)

Matrice=[[1,2],[2,3]]

Matrice=np.array(Matrice)
Matrice=Matrice.astype(float)

i=widgets.BoundedIntText(
    value=1,
    min=0,
    max=len(Matrice),
    step=1,
    description='Ligne i:',
    disabled=False
)

j=widgets.BoundedIntText(
    value=1,
    min=0,
    max=len(Matrice),
    step=1,
    description='Ligne j:',
    disabled=False
)
a= 1;
a=np.copy(Matrice)
print(a, Matrice)
def f(w1,w2,w3,w4,w5):
    i,j=al.python2matlab(w2,w3)
    print(a, Matrice)
    w4=eval(w4)
    if w4==0:
        print('Le coefficient alpha doit être non-nul!')
        return
    if w1=='Eij':
        w5=al.Eij(w5,i,j)
        al.printEquMatrices([Matrice,w5,a])
        print('Opération élémentaire', w1, 'échange la ligne', w2,' avec la ligne ',w3)
    if w1=='Ei(alpha)':
        w5=al.Ealpha(w5,i,w4)
        al.printEquMatrices([Matrice2,w5])
        print('Opération élémentaire', w1, 'multiplie la ligne', w3,' par',w4 )
    if w1=='Eij(alpha)':
        w5=al.Eijalpha(w5,i,j,w4)
        al.printEquMatrices([Matrice2,w5])
        print('Opération élémentaire', w1, 'additionne', w4,' fois la ligne ',w3, 'à la ligne',w2 )


interact_manual(f, w1=r, w2=i,w3=j,w4=alpha, w5=fixed(Matrice))


[[1. 2.]
 [2. 3.]] [[1. 2.]
 [2. 3.]]


interactive(children=(RadioButtons(description='Opération:', options=('Eij', 'Ei(alpha)', 'Eij(alpha)'), value…

<function __main__.f(w1, w2, w3, w4, w5)>

In [1]:
import numpy as np
import AL_Fct as al
from IPython.display import display, Latex

M=[[1,2],[2,3]]
b=[1,1]
al.printSyst(2,2,M,b)
B=np.matrix([]).astype(float)
print(str(B)=='[]' or str(B)=='')
N=np.matrix(M).astype(float)
P=np.array(M)
print('M',type(M), len(M), len(M[0]))
print('N', type(N), len(N), len(N[0]), N.shape)
print('P', type(P), len(P), len(P[0]), P[0:])
display(Latex('$' + al.texMatrix(N,b) + '$'))
al.printA(N,b)
al.printEquMatrices(N,b)

[
(1, 2) (2, 1)
[1 2 1]
[2 3 1]


<IPython.core.display.Latex object>

True
M <class 'list'> 2 2
N <class 'numpy.matrix'> 2 1 (2, 2)
P <class 'numpy.ndarray'> 2 2 [[1 2]
 [2 3]]


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [2]:

import ipywidgets as widgets
import numpy as np
from ipywidgets import interact, interactive, fixed, interact_manual
import AL_Fct as al
Matrice=[[1,2,3],[4,5,6],[7,8,9]]
b=[[1,0,0],[0,1,0], [0,0,1]]


Matrice=np.array(Matrice).astype(float)
b=np.array(b).astype(float)


print('Vous allez échelonner la matrice')
al.printAAug(Matrice,b)
j=widgets.BoundedIntText(
    value=1,
    min=1,
    max=len(Matrice),
    step=1,
    description='Ligne j:',
    disabled=False
)
i=widgets.BoundedIntText(
    value=1,
    min=1,
    max=len(Matrice),
    step=1,
    description='Ligne i:',
    disabled=False
)

r=widgets.RadioButtons(
    options=['Eij', 'Ei(alpha)', 'Eij(alpha)'],
    description='Opération:',
    disabled=False
)


alpha=widgets.Text(
    value='1',
    description='Coeff. alpha:',
    disabled=False
)

print("Régler les paramètres et évaluer la cellule suivante")
print("Répéter cela jusqu'à obtenir une forme échelonnée réduite")
display(r)
display(i)
display(j)
display(alpha)


MatriceList=[Matrice]
RhSList=[b]


Vous allez échelonner la matrice


<IPython.core.display.Latex object>

Régler les paramètres et évaluer la cellule suivante
Répéter cela jusqu'à obtenir une forme échelonnée réduite


RadioButtons(description='Opération:', options=('Eij', 'Ei(alpha)', 'Eij(alpha)'), value='Eij')

BoundedIntText(value=1, description='Ligne i:', max=3, min=1)

BoundedIntText(value=1, description='Ligne j:', max=3, min=1)

Text(value='1', description='Coeff. alpha:')

In [1]:

import ipywidgets as widgets
import numpy as np
from ipywidgets import interact, interactive, fixed, interact_manual
import AL_Fct as al
A=[[1,2,3],[4,5,6],[7,8,9]]
b=[[1,0,0],[0,1,0], [0,0,1]]
print('Vous allez échelonner la matrice')
al.printAAug(A,b)
[i,j,r,alpha]= al.manualEch(A,b)
m=np.concatenate((A,b), axis=1)
MatriceList=[A]
RhSList=[b]


Vous allez échelonner la matrice


<IPython.core.display.Latex object>

Régler les paramètres et évaluer la cellule suivante
Répéter cela jusqu'à obtenir une forme échelonnée réduite


RadioButtons(description='Opération:', options=('Eij', 'Ei(alpha)', 'Eij(alpha)'), value='Eij')

BoundedIntText(value=1, description='Ligne i:', max=3, min=1)

BoundedIntText(value=1, description='Ligne j:', max=3, min=1)

Text(value='1', description='Coeff. alpha:')

In [2]:
if alpha.value==0:
    print('Le coefficient alpha doit être non-nul!')
if r.value=='Eij':
    m=al.Eij(m,i.value-1,j.value-1)
if r.value=='Ei(alpha)':
    m=al.Ealpha(m,i.value-1,eval(alpha.value))
if r.value=='Eij(alpha)':
    m=al.Eijalpha(m,i.value-1,j.value-1,eval(alpha.value))
A=np.asmatrix(A)    
print(A[0])
#MatriceList.append(m[:,0:len(A[0])])
#RhSList.append(m[:,len(A[0]):])
MatriceList.append(m[:,0:A.shape[1]])
RhSList.append(m[:,A.shape[1]:])
al.printEquMatricesAug(MatriceList,RhSList)


[[1 2 3]]


<IPython.core.display.Latex object>