# Concept(s)-clé(s) et théorie


In [1]:
import AL_Fct as al
import numpy as np
import ipywidgets as widgets
import random

from ipywidgets import interact, interactive, fixed, interact_manual

### **Exercice 1**

À l'aide des opérations élémentaires, échelonner et réduire les matrices ci-dessous.

$$
\begin{pmatrix}
2 & -1\\
1 &2
\end{pmatrix}\hskip2em
\begin{pmatrix}
\dfrac{1}{2} & 3 & 0\\
2 & -4 & 6\\
1 & 3 &-1
\end{pmatrix}\hskip2em
\begin{pmatrix}
1 & 0 &1\\
0 & 1 & -1\\
1 & 1 &-1
\end{pmatrix}
$$

In [2]:
A=[[2,-1], [1,2]]

In [3]:
print('Vous allez échelonner la matrice')
al.printA(A)
[i,j,r,alpha]= al.manualEch(A)
MatriceList=[A]
m=np.matrix(A)

Vous allez échelonner la matrice


<IPython.core.display.Latex object>

Régler les paramètres et évaluer la cellule suivante
Répéter cela jusqu'à obtenir une forme échelonnée réduite


RadioButtons(description='Opération:', options=('Eij', 'Ei(alpha)', 'Eij(alpha)'), value='Eij')

BoundedIntText(value=1, description='Ligne i:', max=2, min=1)

BoundedIntText(value=1, description='Ligne j:', max=2, min=1)

Text(value='1', description='Coeff. alpha:')

In [4]:
al.echelonnage(i,j,r,alpha,A,m,MatriceList)

<IPython.core.display.Latex object>

### **VERIFICATION**
À l'aide des cellules ci-dessous, vous pouvez entrer la matrice (des coefficients ou augmentée) de votre choix et obtenir une forme échelonnée et sa forme échelonnée réduite.

Pour **les formes échelonnées** on utilise la syntaxe suivante

1. Pour la matrice $A$ : al.echelonMat('E', A)
2. Pour la matrice augmentée $(A | b)$ : al.echelonMat('E', A, b)

Pour obenir **les formes échelonnées réduites** mettez 'ER' au lieu de 'E'

In [5]:
import AL_Fct as al
import numpy as np
import ipywidgets as widgets
import random
A=[[1,2,3,4], [5,6,7,8], [9,10,11,12]]
b=[[-1],[-2],[-3]]

In [6]:
M=al.echelonMat('ER',A,b)

[[ 1.  2.  3.  4. -1.]
 [ 5.  6.  7.  8. -2.]
 [ 9. 10. 11. 12. -3.]]
La matrice est sous la forme échelonnée


<IPython.core.display.Latex object>

La matrice est sous la forme échelonnée réduite


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>